{
 "title": "ORCA Overview",
 "tags": [
  "ORCA",
  "managed"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "GITLAB_HOST", "query": "git.cldor.psa.cloud.bwi" },
   { "name": "datasource_orca_prometheus", "query": "prometheus" },
   { "name": "datasource_prodgitlab", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "GitLab", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GitLab",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "downsampler": "mean",
     "expression": "$A * $C * $D * $E",
     "reducer": "max",
     "type": "math",
     "upsampler": "fillna"
    }
   ]
  },
  {
   "title": "GitLab Pipelines (latest per project & ref)",
   "type": "table",
   "gridPos": { "h": 9, "w": 15, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "-max(time() - gitlab_ci_pipeline_timestamp{project=~\".*\"}) by (project, ref, kind)"
    },
    {
     "expr": "max(gitlab_ci_pipeline_duration_seconds{project=~\".*\"}) by (project, ref, kind)"
    },
    {
     "expr": "(max(gitlab_ci_pipeline_status{project=~\".*\", status=~\"success\"}) by (project, ref, kind) * 1) > 0 or\n(max(gitlab_ci_pipeline_status{project=~\".*\", status=~\"running\"}) by (project, ref, kind) * 2) > 0 or\n(max(gitlab_ci_pipeline_status{project=~\".*\", status=~\"failed\"}) by (project, ref, kind) * 3) > 0 or\n(max(gitlab_ci_pipeline_status{project=~\".*\", status=~\"canceled\"}) by (project, ref, kind) * 4) > 0 or\n(max(gitlab_ci_pipeline_status{project=~\".*\", status=~\"created\"}) by (project, ref, kind) * 5) > 0 or\n(max(gitlab_ci_pipeline_status{project=~\".*\", status=~\"waiting_for_resource\"}) by (project, ref, kind) * 6) > 0 or\n(max(gitlab_ci_pipeline_status{project=~\".*\", status=~\"preparing\"}) by (project, ref, kind) * 7) > 0 or\n(max(gitlab_ci_pipeline_status{project=~\".*\", status=~\"pending\"}) by (project, ref, kind) * 8) > 0 or\n(max(gitlab_ci_pipeline_status{project=~\".*\", status=~\"skipped\"}) by (project, ref, kind) * 9) > 0 or\n(max(gitlab_ci_pipeline_status{project=~\".*\", status=~\"manual\"}) by (project, ref, kind) * 10) > 0 or\n(max(gitlab_ci_pipeline_status{project=~\".*\", status=~\"scheduled\"}) by (project, ref, kind) * 11) > 0"
    },
    {
     "expr": "max(gitlab_ci_pipeline_id{project=~\".*\"}) by (project, ref, kind, job_name)"
    }
   ]
  },
  { "title": "IntDev", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CIP-DC01 LDAP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"cip-dc01.padi.intdev.cloud.bwi.intranet-bw.de:636\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CIP-DC02 LDAP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 1, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"cip-dc02.padi.intdev.cloud.bwi.intranet-bw.de:636\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CIW-DC03 LDAP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 2, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"ciw-dc03.wad1i.intdev.cloud.bwi.intranet-bw.de:636\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CIW-DC04 LDAP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 3, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"ciw-dc04.wad1i.intdev.cloud.bwi.intranet-bw.de:636\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vRO IntDev Admin",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://boe-ind-vra-10.mgmt.intdev.cloud.bwi.intranet-bw.de/vco/api/healthstatus?showConfigurationDetails=false&showDetails=false&startupProbe=false\", job=\"prometheus-blackbox-http-regexp-vro\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vRO IntDev Mandant",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://boe-ind-vra-00.mgmt.intdev.cloud.bwi.intranet-bw.de/vco/api/healthstatus?showConfigurationDetails=false&showDetails=false&startupProbe=false\", job=\"prometheus-blackbox-http-regexp-vro\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AAP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://config.i0000007vpc0000029.svc.intdev.cloud.bwi.intranet-bw.de/api/v2/ping/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AAP Certificate (days)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 1, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor((probe_ssl_earliest_cert_expiry{instance=\"https://config.i0000007vpc0000029.svc.intdev.cloud.bwi.intranet-bw.de/api/v2/ping/\", job=\"prometheus-blackbox-http200\"} - time()) / 86400)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ProvDev", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "DNS - SOA ProvDev",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_dns_query_succeeded{instance=\"199.8.2.33\", job=\"prometheus-blackbox-dns-provdev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS - SOA IntDev",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 1, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_dns_query_succeeded{instance=\"199.8.2.33\", job=\"prometheus-blackbox-dns-intdev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vRO ProvDev AdminDev",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 5, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://boe-prd-vra-21.mgmt.provdev.cloud.bwi.intranet-bw.de/vco/api/healthstatus?showConfigurationDetails=false&showDetails=false&startupProbe=false\", job=\"prometheus-blackbox-http-regexp-vro\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vRO ProvDev AdminStage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://boe-prd-vra-31.mgmt.provdev.cloud.bwi.intranet-bw.de/vco/api/healthstatus?showConfigurationDetails=false&showDetails=false&startupProbe=false\", job=\"prometheus-blackbox-http-regexp-vro\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vRO ProvDev Admin",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 7, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://boe-prd-vra-10.mgmt.provdev.cloud.bwi.intranet-bw.de/vco/api/healthstatus?showConfigurationDetails=false&showDetails=false&startupProbe=false\", job=\"prometheus-blackbox-http-regexp-vro\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}