apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-smtp-credentials
  namespace: dev-monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store
  target:
    name: grafana-smtp-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        username: "{{ .username }}"
        password: '{{ .password }}'
  data:
    - remoteRef:
        key: global/grafana/smtpcredentials
        property: username
      secretKey: username
    - remoteRef:
        key: global/grafana/smtpcredentials
        property: password
      secretKey: password
