apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-auth-generic-oauth-secret
  namespace: dev-monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        client_secret: '{{ .clientsecret }}'
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: global/dex/oidc/grafana
        property: client-secret
      secretKey: clientsecret
