apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ext-pullsecret-ociregistry-scanned
  namespace: provider-gitlab-runner
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store
  target:
    name: pullsecret-ociregistry-scanned
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfig | b64dec }}"
  data:
    - secretKey: dockerconfig
      remoteRef:
        key: orcadev-secrets/data/global/pullsecrets_read
        property: dockerconfig
