apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ext-dex
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: orca-vault-secrets
  target:
    name: ext-dex
    creationPolicy: Owner
  data:
    - secretKey: ldap_host
      remoteRef:
        key: orca-secrets/data/global/ldap/padi
        property: host
    - secretKey: ldap_basedn
      remoteRef:
        key: orca-secrets/data/global/ldap/padi
        property: basedn
    - secretKey: ldap_binddn
      remoteRef:
        key: orca-secrets/data/global/ldap/padi
        property: binddn
    - secretKey: ldap_bindpw
      remoteRef:
        key: orca-secrets/data/global/ldap/padi
        property: bindpw
    - secretKey: grafana_secret
      remoteRef:
        key: orca-secrets/data/cosmo/global/dex/oidc/grafana
        property: client-secret
