apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alert-delete-contactpoints
  namespace: monitoring
  labels:
    orca-grafana-alert: "1"
data:
  grafana-alert-delete-contactpoints.yaml: |-
    apiVersion: 1
    deleteContactPoints:
      - orgId: 1
        uid: de9kkyd4ug5xcc
