{
 "title": "GitLab Omnibus",
 "description": "GitLab Omnibus Dashboard (>= 10.3)",
 "tags": [
  "GitLab",
  "managed"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(up{job=\"node\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Rails Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(up{job=\"gitlab-rails\"})"
    }
   ]
  },
  {
   "title": "Postgres Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(pg_up)" }
   ]
  },
  {
   "title": "Sidekiq Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(up{job=\"gitlab-sidekiq\"})"
    }
   ]
  },
  {
   "title": "Workhorse Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(up{job=\"gitlab-workhorse\"})"
    }
   ]
  },
  {
   "title": "Redis Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "redis_up{instance=\"$node:9121\"}"
    }
   ]
  },
  {
   "title": "Gitaly Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(up{job=\"gitaly\"})"
    }
   ]
  },
  {
   "title": "Node Available Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemAvailable{instance=\"$node:9100\"} / \n  node_memory_MemTotal{instance=\"$node:9100\"})\n  or \n((node_memory_MemFree{instance=\"$node:9100\"} + node_memory_Buffers{instance=\"$node:9100\"} + node_memory_Cached{instance=\"$node:9100\"}) /\n  node_memory_MemTotal{instance=\"$node:9100\"})"
    },
    {
     "expr": "(node_memory_MemAvailable_bytes{instance=\"$node:9100\"} / \n  node_memory_MemTotal_bytes{instance=\"$node:9100\"})\n  or \n((node_memory_MemFree_bytes{instance=\"$node:9100\"} + node_memory_Buffers_bytes{instance=\"$node:9100\"} + node_memory_Cached_bytes{instance=\"$node:9100\"}) /\n  node_memory_MemTotal_bytes{instance=\"$node:9100\"})"
    }
   ]
  },
  {
   "title": "Node Disk Free",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail{fstype!~\"tmpfs\"}) / sum(node_filesystem_size{fstype!~\"tmpfs\"})"
    },
    {
     "expr": "sum(node_filesystem_avail_bytes{fstype!~\"tmpfs\"}) / sum(node_filesystem_size_bytes{fstype!~\"tmpfs\"})"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - avg without (mode,cpu) (rate(node_cpu{mode=\"idle\"}[5m]))"
    },
    {
     "expr": "1 - avg without (mode,cpu) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))"
    }
   ]
  },
  {
   "title": "Sidekiq Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(sidekiq_queue_size)", "legendFormat": "Jobs" }
   ]
  },
  {
   "title": "Workhorse Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.95, rate(gitlab_workhorse_request_duration_seconds_bucket[5m])))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(histogram_quantile(0.95, rate(gitlab_workhorse_request_duration_seconds_bucket[5m])))",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(histogram_quantile(0.95, rate(gitlab_workhorse_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(histogram_quantile(0.95, rate(gitlab_workhorse_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}