apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alert-template
  namespace: monitoring
  labels:
    orca-grafana-alert: "1"
data:
  grafana-alert-template.yaml: |-
    apiVersion: 1
    templates:
      - orgID: 1
        name: orca-mail-template
        template: |-
          {{ define "alerts.message" -}}
          {{ if .Alerts.Firing -}}
          {{ len .Alerts.Firing }} firing alert(s)
          {{ template "alerts.summarize_with_links" .Alerts.Firing }}
          {{- end }}
          {{- if .Alerts.Resolved -}}
          {{ len .Alerts.Resolved }} resolved alert(s)
          {{ template "alerts.summarize_with_links" .Alerts.Resolved }}
          {{- end }}
          {{- end }}

          {{ define "alerts.summarize_with_links" -}}
          {{ range . -}}
          {{ range $k, $v := .Labels }}{{ $k }}={{ $v }} {{ end }}
          {{ index .Annotations "summary" }}
          {{- if eq .Status "firing" }}
          - Silence this alert: {{ .SilenceURL }}{{ end }}
          - View on Grafana: {{ .GeneratorURL }}
          {{ end }}
          {{ end }}
