apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ext-pullsecret-ociregistry
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: orca-vault-secrets
  target:
    name: pullsecret-ociregistry
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfig | b64dec }}"
  data:
    # - secretKey: username
    #   remoteRef:
    #     key: orcadev-secrets/data/global/pullsecrets_read
    #     property: username
    # - secretKey: password
    #   remoteRef:
    #     key: orcadev-secrets/data/global/pullsecrets_read
    #     property: password
    - secretKey: dockerconfig
      remoteRef:
        key: orca-secrets/data/global/nexus
        property: dockerconfig
#    - secretKey: url
#      remoteRef:
#        key: orcadev-secrets/data/global/pullsecrets_read
#        property: url
