apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-access-token
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: orca-vault-secrets
  target:
    name: gitlab-access-token
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        gitlab-access-token: "{{ .token }}"
  data:
    - remoteRef:
        key: orca-secrets/data/cosmo/global/prometheus/blackbox-exporter
        property: gitlab-access-token
      secretKey: token
