apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-orca-config
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: orca-vault-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        alertmanager.yaml: |
          global:
            smtp_smarthost: 'smtp.sgw.cloud.bwi.intranet-bw.de:587'
            smtp_from: 'grafana@cloud-orchestration.svc'
            smtp_auth_username: '{{ .username }}'
            smtp_auth_password: '{{ .password }}'
            smtp_require_tls: true
          templates:
          - '/etc/alertmanager/*.tmpl'
          route:
            receiver: alert-emailer
            group_by: ['alertname', 'priority']
            group_wait: 10s
            repeat_interval: 30m
            routes:
            - receiver: discard
              matchers:
              - namespace=~"cpaas-system|kube-system|sysdig-agent"
          receivers:
          - name: discard
          - name: alert-emailer
            email_configs:
            - to: bwi.fp.cloud-orchestration@bwi.de
  data:
    - remoteRef:
        key: orca-secrets/data/cosmo/global/grafana/smtpcredentials
        property: username
      secretKey: username
    - remoteRef:
        key: orca-secrets/data/cosmo/global/grafana/smtpcredentials
        property: password
      secretKey: password
