apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-ci-pipeline-exporter
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: orca-vault-secrets
  target:
    name: gcpe-access-token
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        gitlabToken: "{{ .token }}"
  data:
    - remoteRef:
        key: orca-secrets/data/cosmo/global/prometheus/gitlab-ci-pipeline-exporter
        property: gitlabToken
      secretKey: token
