apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: orca-vault-secrets
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        username: "{{ .username }}"
        password: '{{ .password }}'
  data:
    - remoteRef:
        key: orca-secrets/data/cosmo/global/grafana/admincredentials
        property: username
      secretKey: username
    - remoteRef:
        key: orca-secrets/data/cosmo/global/grafana/admincredentials
        property: password
      secretKey: password
