apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusterconfig-app
  namespace: argocd-integrator
spec:
  destination:
    namespace: argocd-integrator
    server: https://kubernetes.default.svc
  project: integrator
  sources:
    - repoURL: https://provgitlab.sgw.cloud.bwi.intranet-bw.de/Offen/CldOr_I0000007/argocd-config
      targetRevision: main
      path: cosmo/cluster-resources/manifests
      # ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
