apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: orca-vault-store
  # namespace: external-secrets
spec:
  provider:
    vault:
      server: https://vault.konvoi.svc.intdev.cloud.bwi.intranet-bw.de  # Provider VaultServer
      path: orcadev-secrets                       # Path is the mount path of the Vault KV backend endpoint
      version: "v2"
      namespace: "i0000007"
      caProvider:                                          # optional, if you have CA validation issues
        type: Secret
        namespace: argocd-integrator
        name: pkibw-ca-certs
        key: root-certs.crt
      auth:
        appRole:
          path: orcadev                                    # VaultAppRoleName
          roleRef:
            # namespace: external-secrets
            name: orca-vault-approle
            key: role_id
          secretRef:
            # namespace: external-secrets
            name: orca-vault-approle
            key: secret_id
