apiVersion: v1
kind: ConfigMap
metadata:
  name: orca-grafana-datasource-configmap-prometheus
  labels:
    grafana_datasource: "1"
data:
  datasources-orca.yaml: |-
    apiVersion: 1
    datasources:
      - name: orca-monitoring-prometheus
        type: prometheus
        url: http://kps-orcadev-prometheus.monitoring.svc:9090
        access: proxy
        isDefault: true
        jsonData:
          httpMethod: POST
          timeInterval: 30s
      - name: prodgitlab
        type: prometheus
        url: https://orca-gl-metrics.sgw.cloud.bwi.intranet-bw.de
        access: proxy
        isDefault: false
        jsonData:
          httpMethod: POST
          timeInterval: 30s
      - name: vrops-intdev
        type: vmware-ariaoperations-datasource
        access: proxy
        jsonData:
          authSource: "vIDMAuthSource"
          username:
            name: vrops-intdev-credentials
            key: username
          password:
            name: vrops-intdev-credentials
            key: password
          tlsSkipVerify: false
          host: boe-ind-ops-00.mgmt.intdev.cloud.bwi.intranet-bw.de
      - name: vrops-provdev
        type: vmware-ariaoperations-datasource
        access: proxy
        jsonData:
          authSource: "vIDMAuthSource"
          username: "${vrops-provdev-credentials:username}"
          password: "${vrops-provdev-credentials:password}"
          tlsSkipVerify: false
          host: boe-prd-ops-00.mgmt.provdev.cloud.bwi.intranet-bw.de
