apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ext-secret-provider-gitlab-runner-token
  namespace: provider-gitlab-runner
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: orca-vault-secrets
  target:
    name: provider-gitlab-runner-token
    creationPolicy: Owner
    template:
      data:
        runner-registration-token: "{{ .runnertoken }}"
        runner-token: "{{ .runnertoken }}"
  data:
    - secretKey: runnertoken  # runner-registration-token
      remoteRef:
        key: orcadev-secrets/data/provider-gitlab-runner/config
        property: token
